name = input("ENTER YOYR NAME")
age = input("ENTER YOUR AGE")
city = input("ENTER YOYR CITY")
print ("\n---NAME TAG---")
print("-----")
print ("NAME:", name)
print ("AGE:", age)
print ("CITY:", city)
print ("\nLOADING", end="")
print (".", end="")
print (".", end="")
print (".", end="")